[pytest]
asyncio_mode = auto
pythonpath = .
testpaths = tests
asyncio_default_fixture_loop_scope = function
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning
    ignore::pytest.PytestDeprecationWarning
markers =
    asyncio: asyncio-based tests